version: '2'
services: 
  db_odoo: 
    container_name: db_odoo
    environment: 
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    expose: 
      - "5432"
    image: "postgres:9.4"
    network_mode: bridge
    volumes: 
      - "../code/data/postgresql:/var/lib/postgresql/data"
  odoo: 
    container_name: bibind
    depends_on: 
      - db_odoo
    environment: 
      - PGHOST=db_odoo
      - PGUSER=odoo
      - PGPASSWORD=odoo
    image: "bibind/plateforme-base:ansible"
    links: 
      - db_odoo
    network_mode: bridge
    ports: 
      - "8069:8069"
    tty: true
    volumes: 
      - "../code/config:/etc/odoo"
      - "../code/bibind-addons:/mnt/extra-addons"
      - "../code/filestore:/var/lib/odoo/filestore"
  rancher: 
    container_name: rancher-server
    image: "rancher/server:latest"
    ports: 
      - "8080:8080"