version: '2'
services:
  lb-monsiteweb:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.service.external_dns: never
  monsiteweb-live:
    image: wordpress
    stdin_open: true
    tty: true
    links:
    - monsiteweb-db-live:mysql
    ports:
    - 8086:80/tcp
    labels:
      io.rancher.container.pull_image: always
  monsiteweb-db-dev:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  monsiteweb-test:
    image: wordpress
    stdin_open: true
    tty: true
    links:
    - monsiteweb-db-test:mysql
    ports:
    - 8085:80/tcp
    labels:
      io.rancher.container.pull_image: always
  monsiteweb-db-test:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpresstest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  monsiteweb-db-live:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpresslive
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  monsiteweb-dev:
    image: wordpress
    stdin_open: true
    tty: true
    links:
    - monsiteweb-db-dev:mysql
    ports:
    - 8084:80/tcp
    labels:
      io.rancher.container.pull_image: always